apiVersion: v1
kind: Service
metadata:
  name: postgres-external-service
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer