apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq-container
          image: rabbitmq:latest
          ports:
            - containerPort: 5672
          env:
            - name: RABBIT_MQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: rabbitmq_user
            - name: RABBIT_MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: rabbitmq_password
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
