apiVersion: v1
kind: Secret
metadata:
  name: application-secrets
type: Opaque
data:
  postgres_user: cG9zdGdyZXM=
  postgres_password: YWRtaW5AMTIz

  rabbitmq_user: Z3Vlc3Q=
  rabbitmq_password: Z3Vlc3Q=