apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-persistent-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq-container
          image: rabbitmq:latest
          ports:
            - containerPort: 5672
          env:
            - name: RABBIT_MQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: application-configmap
                  key: rabbit_mq_host
            - name: RABBIT_MQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: rabbitmq_user
            - name: RABBIT_MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: rabbitmq_password
          volumeMounts:
            - name: rabbitmq-storage
              mountPath: /rabbitmq/data
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  clusterIP: None
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
