name: CI/CD pipeline for MovieTicketBookingSystem app on AWS EKS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


env:
  AWS_REGION: ap-south-1                   # setting my AWS region (Mumbai)
  APP_DEPLOYMENT_YAML: eks-deployment-app.yaml



jobs:
  build-image:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: mvn clean install

      - name: Build Docker image
        run: docker build -t my-spring-app .

      - name: Move Docker image to Github Workspace
        run: |
          IMAGE_ID=$(docker images -q my-spring-app:latest)
          OUTPUT=$(docker inspect --format='{{.GraphDriver.Data.MergedDir}}' $IMAGE_ID)
          mv $OUTPUT $GITHUB_WORKSPACE


  push-to-ecr:
    name: Push Docker Image to ECR
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: eks-movieticketbookingsystem
          IMAGE_TAG: latest

        run: |
          docker tag my-spring-app:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG                                 
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy-to-eks:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: push-to-ecr
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          kubectl apply -f ${{ env.APP_DEPLOYMENT_YAML }}